### PR TITLE
Fixed(?) parsing issue with multi-arg commands with trailing conditional operators.

### PR DESCRIPTION
**Pull request by bdemmy**
Ex:
If GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange" "EDGE TTW Config.ini" == 1

Would parse as:
If (GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange") ("EDGE TTW Config.ini" == 1)

Now parses as:
If (GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange" "EDGE TTW Config.ini") == 1

Ref:
https://discordapp.com/channels/711228477382328331/968169786414596126/1186750916699889815

Unit tests all passing, as well as original bug case.

There may be a better way of fixing this. Please let me know as I would like to improve/contribute more to xNVSE.

### CODE REVIEW

**Comment by bdemmy** [comment]
> Please add a unit test for your changes, see NVSE/unit_tests folder for some examples. The test should fail when ran on xNVSE before your PR and pass with your changes.

Done: it is very basic but I think it should be enough combined with the rest of the suite.

**Comment by bdemmy** [comment]
I am working on another commit for this, I don't actually think some of what I did is necessary

**Comment by bdemmy** [comment]
Should be good now.

**Comment by korri123** [comment]
This looks good to me, nice PR

**Pull request merged**
